# Generated by Django 4.1.3 on 2022-11-08 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishes',
            name='image',
            field=models.ImageField(default='media/default/default.png', upload_to=''),
        ),
    ]
